Log:
  Level: warning # 日志级别: none, error, warning, info, debug 
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # dns配置路径
RouteConfigPath: /etc/XrayR/route.json # 路由配置的路径,
InboundConfigPath: # /etc/XrayR/custom_inbound.json # 自定义入站配置的路径
OutboundConfigPath: /etc/XrayR/custom_outbound.json # 自定义出站配置的路径
ConnectionConfig:
  Handshake: 4 # 握手时间限制，秒
  ConnIdle: 30 # 连接空闲时间限制，秒
  UplinkOnly: 2 # 下游连接关闭时的时间限制，秒
  DownlinkOnly: 4 # 上行关闭后连接关闭的时间限制，秒
  BufferSize: 64 # 每个连接内部缓存大小，kB
Nodes:
  -
    PanelType: "SSpanel" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "http://127.0.0.1:667"
      ApiKey: "123"
      NodeID: 1
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # api请求超时
      EnableVless: true # 为 V2ray 类型启用 Vless
      VlessFlow: "xtls-rprx-vision" # 仅支持 vless
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, 本地设置将取代远程设置, 0 表示禁用
      DeviceLimit: 0 # 本地设置将取代远程设置，0表示禁用
      RuleListPath: /etc/XrayR/rulelist # Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # 你要监听的IP地址
      SendIP: 0.0.0.0 # 你要发送包的IP地址
      UpdatePeriodic: 60 # 更新nodeinfo的时间，多少秒。
      EnableDNS: false # 使用自定义 DNS 配置，请确保正确设置 dns.json
      DNSType: AsIs # AsIs、UseIP、UseIPv4、UseIPv6、DNS 策略
      EnableProxyProtocol: false # 仅适用于 WebSocket 和 TCP
      AutoSpeedLimitConfig:
        Limit: 0 #警告速度。 设置为 0 以禁用 AutoSpeedLimit (mbps)
        WarnTimes: 0 # 连续警告(WarnTimes)次后，用户将被限制。 设置为0立即惩罚超速用户。
        LimitSpeed: 0 # 受限用户的速度限制（单位：mbps）
        LimitDuration: 0 # 限制持续多少分钟（单位：分钟）
      GlobalDeviceLimitConfig:
        Enable: false #启用某个用户的全局设备限制
        RedisAddr: 127.0.0.1:6379 # redis服务器地址
        RedisPassword: YOUR PASSWORD # Redis 密码
        RedisDB: 0 # Redis 数据库
        Timeout: 5 # redis请求超时
        Expiry: 60 # 过期时间（秒）
      EnableFallback: false # 仅支持 Trojan 和 Vless
      FallBackConfigs:  # 支持多种后备
        -
          SNI: # TLS SNI（服务器名称指示），任何都为空
          Alpn: # Alpn, 任何都为空
          Path: # HTTP PATH，任何都为空
          Dest: 80 #必需，回退的目标，查看
          ProxyProtocolVer: 0 # 发送PROXY协议版本，0表示禁用
       EnableREALITY: false #是否开启REALITY
       DisableLocalREALITYConfig: true # 是否忽略本地 REALITY 配置
       REALITYConfigs: # 本地 REALITY 配置
         Show: false # 显示 REALITY 调试
         Dest：m.media-amazon.com:443 # REALITY 目标地址
         ProxyProtocolVer: 0 # 发送PROXY协议版本，0表示禁用
         ServerNames: # 必填，客户端可用的服务器名称列表，* 目前不支持通配符。
           - m.media-amazon.com
         PrivateKey: #可不填
         MinClientVer: # 可选，Xray客户端的最低版本，格式为x.y.z。
         MaxClientVer: # 可选，Xray客户端的最大版本，格式为x.y.z。
         MaxTimeDiff: 0 # 可选，允许的最大时间差，单位为毫秒。
         ShortIds: #可不填
           -“”
      CertConfig:
        CertMode: dns # 如何获取证书的选项: none, file, http, tls, dns。 选择“none”将强制禁用 tls 配置。
        CertDomain: "node1.test.com" # 证书域名
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS 提供商使用的 DNS ENV 选项
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb
